=begin
require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/prayer_requests", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # PrayerRequest. As you add validations to PrayerRequest, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      PrayerRequest.create! valid_attributes
      get prayer_requests_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      prayer_request = PrayerRequest.create! valid_attributes
      get prayer_request_url(prayer_request)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_prayer_request_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      prayer_request = PrayerRequest.create! valid_attributes
      get edit_prayer_request_url(prayer_request)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new PrayerRequest" do
        expect {
          post prayer_requests_url, params: { prayer_request: valid_attributes }
        }.to change(PrayerRequest, :count).by(1)
      end

      it "redirects to the created prayer_request" do
        post prayer_requests_url, params: { prayer_request: valid_attributes }
        expect(response).to redirect_to(prayer_request_url(PrayerRequest.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new PrayerRequest" do
        expect {
          post prayer_requests_url, params: { prayer_request: invalid_attributes }
        }.to change(PrayerRequest, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post prayer_requests_url, params: { prayer_request: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested prayer_request" do
        prayer_request = PrayerRequest.create! valid_attributes
        patch prayer_request_url(prayer_request), params: { prayer_request: new_attributes }
        prayer_request.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the prayer_request" do
        prayer_request = PrayerRequest.create! valid_attributes
        patch prayer_request_url(prayer_request), params: { prayer_request: new_attributes }
        prayer_request.reload
        expect(response).to redirect_to(prayer_request_url(prayer_request))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        prayer_request = PrayerRequest.create! valid_attributes
        patch prayer_request_url(prayer_request), params: { prayer_request: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested prayer_request" do
      prayer_request = PrayerRequest.create! valid_attributes
      expect {
        delete prayer_request_url(prayer_request)
      }.to change(PrayerRequest, :count).by(-1)
    end

    it "redirects to the prayer_requests list" do
      prayer_request = PrayerRequest.create! valid_attributes
      delete prayer_request_url(prayer_request)
      expect(response).to redirect_to(prayer_requests_url)
    end
  end
end
=end